### ISSUE TITLE
prepare_data function error

### ISSUE THREAD

**Issue by dmunao** [benmarwick/smps#1]
Hi, 

just a short introduction to say that I am a complete beginner with R. Any kind of help is really appreciated, but I could understand if you cannot cover the issue since the beginning.

Following this post on <http://stackoverflow.com/questions/36014676/use-r-to-recreate-contour-plot-made-in-igor> I tried to install and use your package on my dataset. Unfortunately, the prepare_data function returns me this error:

Error in can_take_these_rows$starts[i]:can_take_these_rows$ends[i] : NA/NaN argument

Is there a specific format in which the CSV file has to be formatted? 

Please find attached a sample of my dataset.

Thanks for your attention and your kind support.

David.

[dataset.csv.zip](https://github.com/benmarwick/smps/files/799203/dataset.csv.zip)

**Comment by benmarwick** [comment]
Hi David,

At at glance I can see that you have an extra column at the start, your data format is different to what's expected, your particle sizes are different to what's expected (I think this is the source of the error that you mentioned), and your counts are much smaller. 

Are you using the same instrument? I'm comparing your data to the data included this package (which is the kind of data that the package functions are expecting), which you can see at https://github.com/benmarwick/smps/blob/master/data-raw/contour_plot_data.csv or by running 

```
library(smps)
data("my_data")
View(my_data)
```

**Comment by Serinazhao** [comment]
Hi Ben, first thanks a lot for the effort to make smps package. 
I got the same problem as David: Error in can_take_these_rows$starts[i]:can_take_these_rows$ends[i] : NA/NaN argument, 
and my SMPS have different diameter range from package example "my_data", so I modified the code here to my particle size:
 na <- ifelse(complete.cases(dat),
               ifelse(  dat$X8.753> 0 &
                          dat$X9.002 > 0 &
                          dat$X9.521 > 0 &
                          dat$X10.070 > 0, "ok",
                        "not ok"), "not ok")
this part works, but now I got the different error: 
Error in interp.old(x, y, z, xo, yo, ncp = 0, extrap = FALSE, duplicate = duplicate,  :   all data collinear

I can't find the where is the "interp.old", so don't know what is wrong....

wish you both could get my message, and thanks in advance!

Serina

**Comment by Serinazhao** [comment]
by the way my data example.

[size distribution.xlsx](https://github.com/benmarwick/smps/files/810315/size.distribution.xlsx)

Serina

**Comment by ghost** [comment]
Hi Serina.. I know your questions were years ago but.. did you find a solution for that issue? I'm having the same ones. Thanks

**Comment by kunalbali** [comment]
Hi,
I am trying to plot SMPS data, But I have got the error, screenshot is attached.
Any idea? 
<img width="724" alt="Screenshot 2023-12-21 at 4 16 41 PM" src="https://github.com/benmarwick/smps/assets/6864691/00d7f596-6d32-40bf-8df3-c0c4f836fb2c">

**Comment by zwe1515** [comment]
Hello Ben

When I prepare my data to plot smps, I got the error: Error in can_take_these_rows$starts[i]:can_take_these_rows$ends[i] : 
  NA/NaN argument. Please help me to solve this error. My data file is as follow.
[dataset 1.xlsx](https://github.com/benmarwick/smps/files/13992280/dataset.1.xlsx)

**Comment by benmarwick** [comment]
Hello everyone, this package is no longer actively maintained. I'm sorry that we cannot support any users and provide assistance with errors. If you are an expert R user and interested to take over as maintainer of the package and provide support, please contact us using the contact information in the DESCRIPTION file.
