### ISSUE TITLE
error when installing in R studio and possible sollution

### ISSUE THREAD

**Issue by angelina1898** [benmarwick/smps#3]
When I install smps package according to the following code:
` install.packages("devtools")
devtools::install_github("benmarwick/smps")
library(smps)`

There is error as following:
`'enexprs' is not an exported object from 'namespace:rlang'`

I tried to update ‘rlang’ package in R studio but it didn't work. And then I searched online and found a possible way to solve this problem. Here is it:
Before you install smps package, you'd better install the dev version of rlang from github first. The code is `# install.packages("devtools")
devtools::install_github("r-lib/rlang", build_vignettes = TRUE)`
The reference link: [https://github.com/talgalili/heatmaply/issues/146](url), [https://github.com/r-lib/rlang](url)

I hope it will be helpful if you encounter the same problem as I did.

**Comment by benmarwick** [comment]
Thanks for that update, very kind of you to include the solution also!
