### ISSUE TITLE
prepare_data function error

### ISSUE THREAD

**Issue by htrou** [benmarwick/smps#5]
I attempted to use the prepare_data function on my data and get the following error
```
Error in interp.old(x, y, z, xo, yo, ncp = 0, extrap = FALSE, duplicate = duplicate,  : 
  all data collinear
In addition: Warning messages:
1: In prepare_data(dat) : NAs introduced by coercion
2: In prepare_data(dat) : NAs introduced by coercion
```

Now I'm a little confused, as I have another dataset from a different day that works perfectly fine. The two datasets are identical, except of course for dates and concentrations. As far as I can see, there's no good reason for this error. 
I have attached the two datasets. SM1020.csv is the one that is working fine, SM1021.csv is the one that is not. 
Thank you in advance for any advice you can offer.

Best regards,
Haydn
[SM1020-21.zip](https://github.com/benmarwick/smps/files/3914987/SM1020-21.zip)

**Comment by htrou** [comment]
I found out the issue. The time needs to be in hh:mm, not hh:mm:ss. SM1021 had the latter. 
It's a little annoying, since I have 8 weeks of data that I'll need to change the time format for, but I'm just glad it's working

**Comment by benmarwick** [comment]
Thanks for your note and update, glad to hear you got it sorted.
