### ISSUE TITLE
data format

### ISSUE THREAD

**Issue by sanchezgama** [benmarwick/smps#8]
Hi! I'm wondering what's exactly the format for the data to upload. I'm having issues since the begging:
after "prepare_data(test1)"

Update: converting data from wide to long format...
Update: wide to long format conversion complete...
Update: the data has 1 runs of consecutive measurements. I will interpolate each run separately...
Update: preparing to interpolate...
Update: now working on run 1 ...
Update: run 1 will be divided into 17 chunks for interpolation...
[1] "Update: Interpolating chunk 1 of 17 chunks..."
Error in interp.old(x, y, z, xo, yo, ncp = 0, extrap = FALSE, duplicate = duplicate,  : 
  all data collinear

Attached is the file I'm uploading just in case.. it is from a NanoDMA fyi
[test1.csv](https://github.com/benmarwick/smps/files/7776731/test1.csv)

**Comment by benmarwick** [comment]
Hello, the data format should match exactly what is in our contour_plot_data.csv here https://github.com/benmarwick/smps/blob/master/data-raw/contour_plot_data.csv
